// In the first step the nodeArray is 
// beeing generated by the function 
// createNodes. Afterwards we select the 
// id VIS from out html and append an 
// SVG object.
function setup(rawData) {
    var nodeData = createNodes(rawData);
    
    var vis = d3.select("#barChart").append("svg")
        .attr("width", 960)
        .attr("height", 960);
    
       
    var nodes = vis.selectAll("circle")
                        .data(nodeData)
                        .enter()
                        .append("circle");

    var nodeAttributes = nodes
                       .attr("cx", function (d) { return d.count; })
                       .attr("cy", function (d) { return d.count; })
                       .attr("r", function (d) { return d.fav; })
                       .style("fill", function(d) { return "red"; });

}

// generates nodes from raw csv data
// and return the array containing
// the objects.
function createNodes(rawData) {
    var myNodes = rawData.map(function(d)  {
        return {
            tag : d.tag,
            count : d.count,
            comment : d.comment,
            answer : d.answer,
            fav : d.fav,
            score : d.score,
            view : d.view
        };
    });
    return myNodes;
}

// Load the data to an array and
// send it to funtion setup
// -> this is also the entry point
d3.csv('data/test.csv', setup);
